# Generated by Django 2.2 on 2021-01-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20210109_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetlike',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
